version: "3"
services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "81:8080"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile

    restart: always
    ports:
      - "82:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      -DSN: "host=postgres port=5430 user=postgres password=password dbname=users sslmode=disable timeout=UTC connect_timeout=5"

  postgres:
    image: "postgres:14.0-alpine"
    ports:
      - "5430:5430"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      -POSTGRES_USER: "postgres"
      -POSTGRES_PASSWORD: "password"
      -POSTRGRES_DB: "users"
      -POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
